swagger: "2.0"
info:
  description: "Api para soportar las features de Foodie app y Foodie web"
  version: "1.0.0"
  title: "Foodie"
host: "t2-foodie-server.herokuapp.com"
basePath: "/api/v1"
schemes:
- "https"
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth:
    $ref: "/static/paths/auth.yml"
  /auth/google:
    $ref: "/static/paths/auth_google.yml"
  /auth/recovery_token:
    $ref: "/static/paths/recovery_token.yml"
  /auth/password:
    $ref: "/static/paths/password.yml"
  /available_deliveries:
    $ref: "/static/paths/available_deliveries.yml"

