swagger: "2.0"
info:
  description: "Api para soportar las features de Foodie app y Foodie web"
  version: "1.0.0"
  title: "Foodie"
host: "t2-foodie-server.herokuapp.com"
basePath: "/api/v1"
schemes:
- "https"
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth:
    $ref: "/static/paths/auth.yml"
  /auth/google:
    $ref: "/static/paths/auth_google.yml"
  /auth/password:
    $ref: "/static/paths/auth_password.yml"
  /auth/recovery_token:
    $ref: "/static/paths/auth_recovery_token.yml"
  /available_deliveries:
    $ref: "/static/paths/available_deliveries.yml"
  /chat/{chat_id}:
    $ref: "/static/paths/chat_chat_id.yml"
  /chat/{chat_id}/message:
    $ref: "/static/paths/chat_chat_id_message.yml"
  /orders:
    $ref: "/static/paths/orders.yml"
  /orders/{order_id}:
    $ref: "/static/paths/orders_order_id.yml"
  /orders/{order_id}/quotation:
    $ref: "/static/paths/orders_order_id_quotation.yml"
  /orders/favors:
    $ref: "/static/paths/orders_favors.yml"
  /orders/placed:
    $ref: "/static/paths/orders_placed.yml"
  /orders/directions:
    $ref: "/static/paths/orders_directions.yml"
  /places:
    $ref: "/static/paths/places.yml"
  /products:
    $ref: "/static/paths/products.yml"
  /users:
    $ref: "/static/paths/users.yml"
  /users/me:
    $ref: "/static/paths/users_me.yml"
  /users/{user_id}:
    $ref: "/static/paths/users_user_id.yml"
  /user_ratings:
    $ref: "/static/paths/user_ratings.yml"
  /statistics/registrations:
    $ref: "/static/paths/statistics_registrations.yml"
  /statistics/completed_orders:
    $ref: "/static/paths/statistics_completed_orders.yml"
  /statistics/cancelled_orders:
    $ref: "/static/paths/statistics_cancelled_orders.yml"
  /rules:
    $ref: "/static/paths/rules.yml"
  /rules/rule_id:
    $ref: "/static/paths/rules_rule_id.yml"
  /rules/rule_id/redeem:
    $ref: "/static/paths/rules_rule_id_redeem.yml"
  /rules/rule_id/history:
    $ref: "/static/paths/rules_rule_id_history.yml"
  /rules/benefits:
    $ref: "/static/paths/rules_benefits.yml"
  /rules/redeemable:
    $ref: "/static/paths/rules_redeemable.yml"
  /rules/variables:
    $ref: "/static/paths/rules_variables.yml"
  /rules/operators:
    $ref: "/static/paths/rules_operators.yml"
  /rules/consequence_types:
    $ref: "/static/paths/rules_consequence_types.yml"
