swagger: "2.0"
info:
  description: "Api para soportar las features de Foodie app y Foodie web"
  version: "1.0.0"
  title: "Foodie"
host: "t2-foodie-server.herokuapp.com"
basePath: "/api/v1"
schemes:
- "https"
consumes:
  - application/json
produces:
  - application/json
paths:
  /auth:
    post:
      summary: "Obtener un JWT para la autenticaci贸n"
      parameters:
      - in: "body"
        name: "Autenticaci贸n"
        description: "Datos de la persona a autenticar"
        required: true
        schema:
          $ref: "#/definitions/auth_request"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/auth_response"
        401:
          description: "Unauthorized"
  /auth/google:
    post:
      summary: "Obtener un JWT para la autenticaci贸n"
      parameters:
        - in: "body"
          name: "Autenticaci贸n"
          description: "Token de google para ingresar"
          required: true
          schema:
            $ref: "#/definitions/auth_google_request"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/auth_response"
        401:
          description: "Unauthorized"
definitions:
  auth_request:
    type: "object"
    properties:
      email:
        type: "string"
        example: "foo@email.com"
      password:
        type: "string"
        example: "password"
  auth__google_request:
    type: "object"
    properties:
      token:
        type: "string"
        example: "xxx"
  auth_response:
    type: "object"
    properties:
      token:
        type: "string"
        example: "xxxxx.yyyyy.zzzzz"
      id:
        type: "string"
        example: "123"
